 
services:
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./michael-bidencope
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    