 
services:
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./back-end:/app
  frontend:
    build:
      context: ./michael-bidencope
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./michael-bidencope:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: dev
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    